package com.modoensayo.venues.enums;

public enum TipoDocumentoSede {
    RUT_EMPRESA,
    CEDULA_IDENTIDAD,
    INICIO_ACTIVIDADES_F4415,
    CERTIFICADO_SITUACION_TRIBUTARIA,
    CONTRATO_ARRIENDO,
    COMPROBANTE_DOMICILIO,
    PERMISO_MUNICIPAL,
    CARPETA_TRIBUTARIA_ELECTRONICA,
    ESCRITURA_CONSTITUCION,
    AUTORIZACION_NOTARIAL_PROPIETARIO,
    CERTIFICADO_IVA,
    PATENTE_COMERCIAL,
    RESOLUCION_SANITARIA,
    OTRO
}
