-- ENUMS (13 native PostgreSQL enums)

-- Classes
CREATE TYPE public.class_status AS ENUM (
  'DRAFT','PUBLISHED','IN_PROGRESS','FULL','CANCELLED','COMPLETED','SUSPENDED','POR_VALIDAR'
);
CREATE TYPE public.nivel_clase AS ENUM ('BASICO','INTERMEDIO','AVANZADO');
CREATE TYPE public.tipo_clase AS ENUM ('PROPIA','ASIGNADA');

-- Venues
CREATE TYPE public.estado_sede AS ENUM ('PENDIENTE_APROBACION','APROBADA','RECHAZADA','SUSPENDIDA');
CREATE TYPE public.tipo_sede AS ENUM ('SEDE','HOME_STUDIO');
CREATE TYPE public.tipo_piso AS ENUM ('MADERA','FLOTANTE','CERAMICO','VINILO','CEMENTO','ALFOMBRA','OTRO');
CREATE TYPE public.tipo_documento_sede AS ENUM (
  'RUT_EMPRESA','CEDULA_IDENTIDAD','INICIO_ACTIVIDADES_F4415','CERTIFICADO_SITUACION_TRIBUTARIA',
  'CONTRATO_ARRIENDO','COMPROBANTE_DOMICILIO','PERMISO_MUNICIPAL','CARPETA_TRIBUTARIA_ELECTRONICA',
  'ESCRITURA_CONSTITUCION','AUTORIZACION_NOTARIAL_PROPIETARIO','CERTIFICADO_IVA','PATENTE_COMERCIAL',
  'RESOLUCION_SANITARIA','OTRO'
);

-- Payments
CREATE TYPE public.payment_status AS ENUM ('RETAINED','RELEASED','REFUND_PENDING','REFUNDED','FAILED');
CREATE TYPE public.payment_session_status AS ENUM ('PENDING','APPROVED','FAILED');

-- Reschedules
CREATE TYPE public.reschedule_status AS ENUM ('PROPOSED','TEACHER_ACCEPTED','TEACHER_REJECTED','COMPLETED');
CREATE TYPE public.response_type AS ENUM ('ACCEPTED','REJECTED','TIMEOUT','RECHAZADO_AUTOMATICO');

-- Reviews
CREATE TYPE public.review_target_type AS ENUM ('CLASS','VENUE','STUDENT');

-- Schedule
CREATE TYPE public.block_status AS ENUM ('AVAILABLE','OCCUPIED','MAINTENANCE');
